# Generated by Django 5.1.4 on 2024-12-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0002_appointment_appointment_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
