# Generated by Django 5.1.4 on 2024-12-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='assigned_user',
        ),
    ]
