# Generated by Django 5.1.4 on 2024-12-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0006_appointment_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='appointmentbooked',
            field=models.BooleanField(default=False),
        ),
    ]
