# Generated by Django 5.1.4 on 2024-12-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0007_customuser_appointmentbooked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='assigned_user',
        ),
    ]
