# Generated by Django 5.1.4 on 2024-12-26 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0008_remove_appointment_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
