# Generated by Django 5.1.4 on 2024-12-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0012_authtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
