# Generated by Django 5.1.4 on 2024-12-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0015_session_session_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_no',
        ),
    ]
