# Generated by Django 5.1.4 on 2024-12-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0016_remove_session_session_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
