# Generated by Django 5.1.4 on 2024-12-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0017_session_session_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('user', 'assigned_user', 'appointment_location'), name='unique_appointment_user_assigned_location'),
        ),
    ]
