# Generated by Django 5.1.4 on 2025-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0018_appointment_unique_appointment_user_assigned_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
