# Generated by Django 5.1.4 on 2025-01-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0019_customuser_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth_token',
        ),
    ]
