# Generated by Django 5.1.4 on 2025-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0020_remove_customuser_auth_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_user_assigned_location',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('user', 'assigned_user', 'appointment_location', 'appointment_count'), name='unique_appointment_user_assigned_location'),
        ),
    ]
